//
//  TRPRecommendationInfoJsonModel.swift
//  TRPRestKit
//
//  Created by Evren Yaşar on 21.05.2018.
//  Copyright © 2018 Evren Yaşar. All rights reserved.
//

import Foundation

/// Indicates a poi that was generated by R.E.
public struct TRPRecommendationInfoJsonModel: Decodable {
    
    /// An Int value. Unique id of poi.
    public var id: Int;
    
}
