//
//  TRPRestKit+Question.swift
//  TRPRestKit
//
//  Created by Tripian Inc on 26.12.2025.
//  Copyright © 2025 Tripian Inc. All rights reserved.
//

import Foundation
import TRPFoundationKit

// MARK: - Question Services
extension TRPRestKit {
    
    /// Returns question array which will be used when creating a trip by requested city Id.
    ///
    /// - Parameters:
    ///   - cityId: Id of the requested City.
    ///   - type: type is an enumaration value that can be `trip` or `profile`.
    ///   Both `trip` and `profile` types are used when creating a trip. `profile` type  is used in user's profile questions.
    ///   - language: language is a String value to declare returned questions language (Optional).
    ///   Currently `French` and `English` are available.
    ///   - completion: A closer in the form of CompletionHandlerWithPagination will be called after request is completed.
    ///  - Important: Completion Handler is an any object which needs to be converted to **[TRPTripQuestionInfoModel]** object.
    public func questions(withCityId cityId: Int,
                          type: TRPQuestionCategory? = .trip,
                          completion: @escaping CompletionHandlerWithPagination) {
        self.completionHandlerWithPagination = completion
        questionServices(cityId: cityId, type: type)
    }
    
    /// Returns question array with type, language and completion handler parameters which will be used during creating trips.
    ///
    /// - Parameters:
    ///   - cityId: Id of the requested City.
    ///   - type: type is an enumaration value that can be `trip` or `profile`.
    ///   Both `trip` and `profile` types are used when creating a trip. `profile` type  is used in user's profile questions.
    ///   - language: language is a String value to declare returned questions language (Optional).
    ///   Currently `French` and `English` are available.
    ///   - completion: A closer in the form of CompletionHandlerWithPagination will be called after request is completed.
    ///  - Important: Completion Handler is an any object which needs to be converted to **[TRPTripQuestionInfoModel]** object.
    public func questions(type: TRPQuestionCategory? = .profile,
                          completion: @escaping CompletionHandlerWithPagination) {
        self.completionHandlerWithPagination = completion
        questionServices(type: type)
    }
    
    /// A services which will be used in question services, manages all task connecting to remote server.
    ///
    /// - Parameters:
    ///   - cityId: id of city
    ///   - questionId: id of question
    ///   - type: type of request. You can use Profile when opening add place in localy mode. You have to use Profile and Trip when creating a trip.
    private func questionServices(cityId: Int? = nil,
                                  type: TRPQuestionCategory? = nil) {
        
        var questionService: TRPQuestionService?
        if let cityId = cityId {
            questionService = TRPQuestionService(cityId: cityId)
        } else {
            questionService = TRPQuestionService(tripType: type ?? .trip)
        }
        
        guard let services = questionService else {return}
        services.tripType = type ?? .trip
        services.completion = {   (result, error, pagination) in
            if let error = error {
                self.postError(error: error)
                return
            }
            guard let serviceResult = result as? TRPQuestionJsonModel, let questions = serviceResult.data else {
                self.postError(error: TRPErrors.emptyDataOrParserError as NSError)
                return
            }
            
            self.postData(result: questions, pagination: pagination)
        }
        services.connection()
    }
    
}

// MARK: - Quick Recommendation
extension TRPRestKit {
    
    /// Returns TRPRecommendationInfoJsonModel list generated by requested TRPRecommendationSettings object.
    ///
    /// `TRPRecommendationSettings(cityId:)` declaration can be used in `Localy Mode`.
    ///  However, in `Trip Mode`,  usage with `TRPRecommendationSettings(hash:)` declaration is suggested.
    ///
    /// - Parameters:
    ///      - settings: A TRPRecommendationSettings object which is retrieved by Recommendation Engine.
    ///      - autoPagination: bool value to declare whether pagination is requested or not (Optional), in a detailed manner,
    ///      if the autopagination is set to `true`, next url will be continued.
    ///      If autopagination is set to `false`, next url will not be continued.
    ///      To call **poi(url:complation:)**, `pagination.nextlink` must be used.
    ///      - completion: A closer in the form of CompletionHandlerWithPagination will be called after request is completed.
    /// - Important: Completion Handler is an any object which needs to be converted to **[TRPRecommendationInfoJsonModel]** object.
    /// - See Also: [Api
    public func quickRecommendation(settings: TRPRecommendationSettings, autoPagination: Bool = true, completion: @escaping CompletionHandlerWithPagination) {
        self.completionHandlerWithPagination = completion
        recommendationServices(settings: settings, autoPagination: autoPagination)
    }
    
    /// A services which will be used in recommendation services, manages all task connecting to remote server.
    private func recommendationServices(settings: TRPRecommendationSettings, autoPagination: Bool) {
        let recommendationService = TRPRecommendation(settings: settings)
        recommendationService.isAutoPagination = autoPagination
        recommendationService.completion = { (result, error, pagination) in
            if let error = error {
                self.postError(error: error)
                return
            }
            recommendationService.completion = { result, error, pagination in
                self.genericParseAndPost([TRPRecommendationInfoJsonModel].self, result, error, pagination)
            }
        }
        recommendationService.connection()
    }
    
}

